export const RoomsData = [
  {
    id: 1,
    stock: 4,
    name: 'Chambre double standard vue mer',
    prix: 90,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    seaView: true,
    images: {},
  },
  {
    id: 2,
    stock: 4,
    name: 'Chambre double standard vue cour',
    prix: 80,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    seaView: false,
  },
  {
    id: 3,
    stock: 2,
    name: 'Chambre twin standard vue cour',
    prix: 80,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 2,
    bedType: 'twin',
    seaView: false,
  },
  {
    id: 4,
    stock: 2,
    name: 'Chambre twin standard vue mer',
    prix: 90,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 2,
    bedType: 'twin',
    seaView: true,
  },
  {
    id: 5,
    stock: 2,
    name: 'Studio double vue mer',
    prix: 110,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    seaView: true,
    kitchen: true,
  },
  {
    id: 6,
    stock: 2,
    name: 'Chambre double economique vue mer (12m²)',
    prix: 85,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    seaView: true,
  },
  {
    id: 7,
    stock: 2,
    name: 'Grand studio double vue mer',
    prix: 150,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 4,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    sofa: 1,
    bedType: 'double',
    seaView: true,
    kitchen: true,
    livingRoom: true,
  },
  {
    id: 7,
    stock: 2,
    name: 'Grand studio twin vue mer',
    prix: 150,
    category: 'Hotel',
    address: '46, boulevard de la plage',
    travelers: 4,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 2,
    sofa: 2,
    bedType: 'twin',
    seaView: true,
    kitchen: true,
    livingRoom: true,
  },
  {
    id: 8,
    stock: 5,
    name: 'Chambre double',
    prix: 70,
    category: 'Gîte',
    address: '13 Rue Garn An Aod',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    kitchen: 'En Commun',
  },
  {
    id: 9,
    stock: 5,
    name: 'Chambre twin',
    prix: 70,
    category: 'Gîte',
    address: '13 Rue Garn An Aod',
    travelers: 2,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'twin',
    kitchen: 'En Commun',
  },
  {
    id: 10,
    stock: 1,
    name: 'Appartement Le Dixmude',
    prix: 150,
    category: 'Appartement',
    address: '2 Rue Dixmude',
    travelers: 4,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    kitchen: true,
    sofa: 1,
    livingRoom: true,
  },
  {
    id: 11,
    stock: 1,
    name: 'Appartement Le Kador',
    prix: 150,
    category: 'Appartement',
    address: '40, boulevard de la plage',
    travelers: 4,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    kitchen: true,
    sofa: 1,
    livingRoom: true,
  },
  {
    id: 12,
    stock: 1,
    name: 'Appartement Le Portzic',
    prix: 150,
    category: 'Appartement',
    address: `1 Rue de l'Atlantique`,
    travelers: 4,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 1,
    bedType: 'double',
    kitchen: true,
    sofa: 1,
    livingRoom: true,
  },
  {
    id: 13,
    stock: 1,
    name: 'Appartement Le Portzic',
    prix: 170,
    category: 'Appartement',
    address: `1 Rue de l'Atlantique`,
    travelers: 6,
    breakfast: '15€',
    bathroom: 'shower',
    bed: 2,
    bedType: 'double',
    kitchen: true,
    sofa: 1,
    livingRoom: true,
  },
];
